name: Delete old workflow runs
on:
  schedule:
    - cron: '0 23 */2 * *'
# Run every two days, at 23:00.
  workflow_dispatch:
   
jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs of this repo
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 3  